#!/nix/store/5hplxs3kprdp6v62qk3di6a1m1s1paiq-bash-4.4-p23/bin/bash
#

# TODO NOTE not using this yet, but will be soon via https://medium.com/@anandmohit7/improving-development-workflow-using-git-hooks-8498f5aa3345

bash ./test.sh
emacsExitCode=$?;

if [ $emacsExitCode -ne 0 ]; then
    echo ""
    echo "========>>>>>>     test.sh failed, cannot push.     <<<<<<========"
    echo ""
fi
exit $emacsExitCode;
